### ISSUE TITLE
NU5104 when depending on a "release" of nng.NET

### ISSUE THREAD

**Issue by TYoungSL** [jeikabu/nng.NETCore#105]
https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu5104

> A stable release of a package should not have a prerelease dependency.

Perhaps release a non-prerelease build?
e.g. something without `-rc0` (a label) on the end of the SemVer string.

**Comment by jeikabu** [comment]
Ah, yes... this...
The main reason(s) I've been using this scheme:

1. Package version matches NNG versions
2. Can still make updates/fixes to nng.NETCore (for the same release of NNG)
3. (To a lesser extent- for my own sanity) It matches [nng_async/runng](https://github.com/jeikabu/runng)

**Comment by jeikabu** [comment]
You’ll have to build/package your own stable release until there’s another solution in .NET.
