### ISSUE TITLE
Add to class message  method GetBodyPtr() for Marshaling

### ISSUE THREAD

**Issue by TomKein** [jeikabu/nng.NETCore#55]
public IntPtr GetBodyPtr() => nng_msg_body(NngMsg);
or
public T AsStruct<T>() => Marshal.PtrToStructure<T>(nng_msg_body(NngMsg));

**Comment by jeikabu** [comment]
I added `IntPtr AsPtr()` so it should work with Marshal (and probably other things as well) in PR#56.
