### ISSUE TITLE
Netcoreapp2.2 target doesn't restore nng.NETCore.dll

### ISSUE THREAD

**Issue by azhmur** [jeikabu/nng.NETCore#59]
Netcoreapp2.2 target projected after adding reference to Subor.NNG.net doesn't put nng.NETCore.dll in right place. Thus you can't use after restore.

PS Package structure quite unusual, didn't get to the root case.

**Comment by jeikabu** [comment]
`dotnet build` should run the `build/Subor.nng.NETCore.targets` targets script and copy assemblies:
```pwsh
dotnet new console -f netcoreapp2.2
dotnet add package Subor.nng.NETCore -v 1.1.1
dotnet build
(Get-ChildItem -Include nng.NETCore.dll -Recurse).FullName
```
Shows 3:
```
bin\Debug\netcoreapp2.2\runtimes\any\lib\net461\nng.NETCore.dll
bin\Debug\netcoreapp2.2\runtimes\any\lib\netstandard1.5\nng.NETCore.dll
bin\Debug\netcoreapp2.2\runtimes\any\lib\netstandard2.0\nng.NETCore.dll
```
