### ISSUE TITLE
Context do not provide any way to get/set options

### ISSUE THREAD

**Issue by denis-troller** [jeikabu/nng.NETCore#61]
Some contextx support options (for example ReqRep support NNG_OPT_REQ_RESENDTIME ).
There is currently no way to set this option.

1. Contexts should at least support `IGetOption`/`ISetOption`
2. Protocol-specific options may be available on the corresponding context with properly named methods (as per SetTimeout on AsyncContext). For example `void IAsyncReqRepContext.SetResendTime(int duration)`

**Comment by jeikabu** [comment]
It's currently convoluted how you'd do it, but there's [an example in `SurveyTests.cs`](https://github.com/jeikabu/nng.NETCore/blob/v1.1.1-0/tests/SurveyTests.cs#L66):  
```cs
var socket = Factory.RequesterOpen().ThenDial(dialUrl).Unwrap();
var ctx = socket.CreateAsyncContext(Factory).Unwrap();
var asyncctx = (ctx as ICtx).Ctx;
asyncctx.SetOpt(Native.Defines.NNG_OPT_REQ_RESENDTIME, /* whatever */);
```

I'll look at making it saner to get an `ICtx`/`INngCtx` and adding `SetResendTime()`.

**Comment by jeikabu** [comment]
It can now be done with:
```csharp
var socket = Factory.RequesterOpen().ThenDial(dialUrl).Unwrap();
var ctx = socket.CreateAsyncContext(Factory).Unwrap();
ctx.Ctx.SetOpt(Native.Defines.NNG_OPT_REQ_RESENDTIME, /* whatever */);
```
