### ISSUE TITLE
listenOrDial is not method.

### ISSUE THREAD

**Issue by seanmars** [jeikabu/nng.NETCore#77]
I'm try to using this wrapper. I follow the examples but got this error.

```
'NngResult<IRepSocket>' does not contain a definition for 'listenOrDial' and no accessible extension method 'listenOrDial' accepting a first argument of type 'NngResult<IRepSocket>' could be found.
```

Is it i missing something? Or there has a new examples project?

**Comment by jeikabu** [comment]
It's only used in the [nngcat example to deal with commandline options](https://github.com/jeikabu/nng.NETCore/blob/master/examples/nngcat/Program.cs#L74).

**Comment by seanmars** [comment]
> It's only used in the [nngcat example to deal with commandline options](https://github.com/jeikabu/nng.NETCore/blob/master/examples/nngcat/Program.cs#L74).

Okay, I see now. I missed it. Thanks :).
