### ISSUE TITLE
Update to nng 1.3

### ISSUE THREAD

**Issue by tomekki** [jeikabu/nng.NETCore#79]
Our team recently run into a dispose bug, which is fixed by now:
https://github.com/nanomsg/nng/commit/c726f93041b8dcd085c88144f2c13a2ac6fe58ad
For this bug alone It would be good to update the wrapper.

**Comment by jeikabu** [comment]
I did some of the initial work in #76 but there were a few test failures I didn't have time to look into. I'll try to wrap that up.

**Comment by jeikabu** [comment]
Our tests are unfortunately generally unreliable, but the behaviour of `nng_msg_clear` definitely changed.  Will see what the response to https://github.com/nanomsg/nng/issues/1252 is, adjust the test accordingly, and then commit #76 .

**Comment by jeikabu** [comment]
We can live with that as a "known issue".
