### ISSUE TITLE
"malloc(): memory corruption (fast)" when using ISendSocket.SendMsg(IMessage)

### ISSUE THREAD

**Issue by biocommando** [jeikabu/nng.NETCore#80]
I encountered an issue where I get "malloc(): memory corruption (fast)" or other similar errors (using .NET Core 3.1 on Linux) when using ISendSocket.SendMsg(IMessage). Here's the minimal program that will reproduce the issue:

```csharp
using System.Threading.Tasks;

using nng;
using System.IO;

namespace NngBug
{
    class Program
    {
        static void Main(string[] args)
        {
            var path = Path.GetDirectoryName(typeof(Program).Assembly.Location);
            var ctx = new nng.NngLoadContext(path);
            var factory = nng.NngLoadContext.Init(ctx);
            var addr = "tcp://127.0.0.1:5000";
            using (var repSocket = factory.ReplierOpen().ThenListen(addr).Unwrap())
            using (var reqSocket = factory.RequesterOpen().ThenDial(addr).Unwrap())
            {
                Task.Run(() =>
                {
                    while (true)
                    {
                        // the code block causing the issue
                        using (var msg = factory.CreateMessage())
                        {
                            msg.Append(new byte[100]);
                            reqSocket.SendMsg(msg).Unwrap();
                        }
                        // if I use this instead it works without errors:
                        // reqSocket.Send(new byte[100]).Unwrap();
                        using (var resp = reqSocket.RecvMsg().Unwrap())
                        {
                        }
                    }
                });
                while (true)
                {
                    using (var msg = repSocket.RecvMsg().Unwrap())
                    {
                        repSocket.Send(new byte[100]);
                    }
                }
            }
        }
    }
}
```

**Comment by jeikabu** [comment]
This with a particular version, or HEAD.

**Comment by jeikabu** [comment]
It's possibly related to [nng_sendmsg](https://nng.nanomsg.org/man/tip/nng_sendmsg.3.html) semantics where on success NNG takes ownership of the message.  But `using` will mean it is Dispose'd by the caller- which calls `free()`.
The behaviour of `ISocket::SendMsg` likely needs to be changed to release ownership of `IMessage::NngMsg` if the calls succeeds.

**Comment by jeikabu** [comment]
That seems to be it.  In [Socket.cs](https://github.com/jeikabu/nng.NETCore/blob/2fa797cfe53bda7d67114ee35e48eb7bf2b34e37/nng.NETCore/Socket.cs#L93) change `SendMsg` to:

```csharp
public NngResult<Unit> SendMsg(IMessage message, Defines.NngFlag flags = default)
        {
            var res = Unit.OkIfZero(nng_sendmsg(NngSocket, message.NngMsg, flags));
            if (res.IsOk())
            {
                var _ = message.Take();
            }
            return res;
        }
```
Let me know if that works for you.  I'll need to check if this is needed elsewhere.

**Comment by biocommando** [comment]
I'm using the (then) latest release version through NuGet (1.2.4-rc0).

When I replace this line `reqSocket.SendMsg(msg).Unwrap();` with the code below the application doesn't crash anymore.

```csharp
var r = reqSocket.SendMsg(msg);
if (r.IsOk()) _ = msg.Take();
r.Unwrap();
```

So yes, your suggested fix does the job :)

**Comment by jeikabu** [comment]
Great I'll go ahead and apply this fix. 

Sorry about the nuget package. My code signing cert expired in January and I finally got a new one.
