### ISSUE TITLE
new nuget package fails to load

### ISSUE THREAD

**Issue by denis-troller** [jeikabu/nng.NETCore#86]
I tried switching from subor.NNG.NETCore to nng.NET (1.3.1-rc0) and my .net Core programs fail to load with an exception stating it cannot load the nng.NETCore.dll assembly.

It seems the code for AssemblyLoadContext still mentions nng.NETCOre.dll, when the new dll bears the nng.NET.dll name.

Is it a bug or did something go wrong in my packages when I switched ?

**Comment by jeikabu** [comment]
Tests should have caught this, I'll look into it. 
Thanks for reporting this.

**Comment by denis-troller** [comment]
any news on this issue ?

**Comment by jeikabu** [comment]
I understand it's an issue and have just been swamped.
The nuget package should definitely get fixed, but are you able to use the source in the mean time?

**Comment by jeikabu** [comment]
Fixed in [v1.3.1-rc1](https://www.nuget.org/packages/nng.NET/1.3.1-rc1)
